plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\tracker\\safemark\\web-redirect"
publishOrigin = "config"
commandOrigin = "ui"
base = "D:\\tracker\\safemark\\web-redirect"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]